"""add an argument to the pitch

Revision ID: c30d4fbb0db6
Revises: a7cfc68366fd
Create Date: 2019-02-27 09:45:00.644757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30d4fbb0db6'
down_revision = 'a7cfc68366fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.String(length=400), nullable=True))
    op.add_column('pitches', sa.Column('teaser', sa.String(length=50), nullable=True))
    op.drop_column('pitches', 'narration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('narration', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'teaser')
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
