"""cange content to the comment model

Revision ID: d7dbcb7ec2e8
Revises: c30d4fbb0db6
Create Date: 2019-02-28 18:47:19.920493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dbcb7ec2e8'
down_revision = 'c30d4fbb0db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=400), nullable=True))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
